name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-prime-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build unit-test
      working-directory: ${{github.workspace}}/worker/lib/PrimeCheck
      run: gcc ./unit_test.cpp ./src/PrimeCheck.cpp -o unit_test.exe -Incruses
  
  test-prime-check:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build unit-test
      working-directory: ${{github.workspace}}/worker/lib/PrimeCheck
      run: gcc ./unit_test.cpp ./src/PrimeCheck.cpp -o unit_test.exe -Incruses

    - name: run unit-test
      working-directory: ${{github.workspace}}/worker/lib/PrimeCheck
      run: ./unit_test.exe
