name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build unit-test
      working-directory: ${{github.workspace}}/worker/prime_check
      run: gcc .\unit_test.cpp .\prime_check.cpp -o unit_test.exe -Incruses
    
    - name: run unit-test
      run: ./unit_test.exe
